name: Consistent Pull Request

on:
  pull_request_target:
    types: [opened, edited, synchronize]

jobs:
  consistent-pull-request:
    name: Consistent Pull Request
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      pull-requests: write
    steps:
      - name: Check pr label name
        uses: agaroot-technologies/action-restrict-pr-label@7afc265323238e3b73f016e565f9c81d5e67362d # v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          rules: |
            main <- feature/* [feature]
            main <- bugfix/* [bugfix]
            main <- refactor/* [refactor]
            main <- chore/* [chore]
            main <- deps/* [deps]

      - name: Check head branch name
        uses: agaroot-technologies/action-restrict-head-branch@48b7777bbd99e4702abe38e4a996fcd5a2453667 # v1.0.0
        with:
          rules: |
            feature/* bugfix/* refactor/* chore/* deps/*

      - name: Check base branch name
        uses: agaroot-technologies/action-restrict-base-branch@824225e012eff11d1d3f44ee5e862af2b7b5f1eb # v1.0.0
        with:
          rules: |
            main <- feature/* bugfix/* refactor/* chore/* deps/*
