name: Consistent Pull Request

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  consistent-pull-request:
    name: Consistent Pull Request
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

      - name: Check head branch name
        if: >-
          github.event.action == 'opened' &&
          github.head_ref != 'main'
        env:
          HEAD_REF: ${{ github.head_ref }}
          PR_NUMBER: ${{ github.event.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if ! [[ "${HEAD_REF}" =~ ^(feature|bugfix|refactor|chore|deps)/.* ]]; then
              echo "::error::Branch name '${HEAD_REF}' does not follow naming convention"
              gh pr close "${PR_NUMBER}"
              exit 1
          fi

      - name: Consistent pull request title and label
        if: >-
          github.event.action != 'synchronize' &&
          github.event.pull_request.state == 'open' &&
          github.head_ref != 'main'
        env:
          HEAD_REF: ${{ github.head_ref }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_NUMBER: ${{ github.event.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          label=$(echo "${HEAD_REF}" | cut -d'/' -f1)
          pr_title_regex="^\[${label}\]"
          if ! [[ "${PR_TITLE}" =~ ${pr_title_regex} ]]; then
            PR_TITLE="[${label}] ${PR_TITLE}"
          fi
          gh pr edit "${PR_NUMBER}" --title "${PR_TITLE}" --add-label "${label}"

      - name: Check base branch name
        if: >-
          github.event.pull_request.state == 'open' &&
          github.head_ref != 'main'
        env:
          BASE_REF: ${{ github.base_ref }}
        run: |
          if ! [[ "${BASE_REF}" =~ ^main$ ]]; then
              echo "::error::Cannot merge into branch name '${BASE_REF}'."
              exit 1
          fi
